spring:
  messages:
    basename: messages,errors
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true 시스템아웃을 통해 찍음
        format_sql: true
  config:
    import: private.yml
#    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
