spring:
  datasource:
    url: ENC(DsZkf4Q5nqBTAhvEYOLugD0KHAc0+4NIcMhn4tRgE+F1wNbCivNkUwrDHWgG+UJcfeECxCSGKp5TqizaWU3OyYJVzUnWcIDT8Gqy6SN3xIkyXIjehBNgval5xqvtcBi/)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(PS3fJXs6ug/WS9mcrEBjcg==)
    password: ENC(xRZQHBGntE5azvTnwLyg36cFkDB0pPbI)
