spring:
  datasource:
    url: jdbc:mysql://hisquare.cwnxhk4tv7sk.ap-northeast-2.rds.amazonaws.com:3306/hisquare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(PS3fJXs6ug/WS9mcrEBjcg==)
    password: ENC(xRZQHBGntE5azvTnwLyg36cFkDB0pPbI)
